-- ==================================================================================
-- 7.3 - Consulta Historia de mensagens enviada de um usuario.sql
-- Objetivo: Listar o histórico de mensagens enviadas por um usuário.
-- Correções:
-- 1. O esquema fornecido não possui uma tabela 'Mensagens'. Para que a consulta funcione, é necessário assumir a existência de uma tabela Mensagem com os campos básicos.
-- 2. A consulta foi escrita com base nessa estrutura lógica.
--    Estrutura assumida: CREATE TABLE Mensagem (ID_Mensagem INT PRIMARY KEY, ID_Remetente INT, Texto TEXT, TimeStamp TIMESTAMP);
-- ==================================================================================
/*
-- Para esta consulta funcionar, uma tabela 'Mensagem' precisa existir.
-- O esquema atual possui apenas 'Usuario_Mensagens', que parece ser uma tabela de junção para destinatários.
-- A estrutura lógica necessária seria:
CREATE TABLE Mensagem (
    ID_Mensagem INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    ID_Remetente INT NOT NULL REFERENCES Usuario(ID_Usuario),
    Texto TEXT,
    TimeStamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
-- A tabela 'Usuario_Mensagens' então ligaria uma mensagem a múltiplos destinatários.

-- A consulta corrigida, baseada na existência dessa tabela, seria:
*/
SELECT
    m.TimeStamp,
    m.Texto
FROM
    Mensagem m -- Usando a tabela 'Mensagem' assumida
JOIN
    Usuario u ON m.ID_Remetente = u.ID_Usuario
WHERE
    u.Email = 'alberto.santos@escola.edu'
ORDER BY
    m.TimeStamp DESC;
